client/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#home"

  post '/posts', to: 'home#create', as: "create_post"
end

client/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

client/app/models/post.rb
class Post < ApplicationRecord
end

client/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

client/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    conn = Faraday.new('http://127.0.0.1:3001')
    response = conn.get('/posts')
    if response.status in 200..299
      @posts = JSON.parse(response.body)
      @posts.each { |post| Post.create!(title: post[:title], text: post[:text]) }
    end
  end
  
  def create
    conn = Faraday.new('http://127.0.0.1:3001')
    response = conn.post do |res|
      res.url '/posts'
      res.headers['Content-Type'] = 'application/json'
      res.body = {
        post: {
          title: params[:title],
          text: params[:text]
        }
      }.to_json
    end

    case response.status
      when 200..299
        # Success: Parse and handle the response body
        created_post = JSON.parse(response.body)
        puts "New post created successfully:"
        puts "Title: #{created_post['title']}, Text: #{created_post['text']}"
      when 400..499
        # Client error: Invalid request
        puts "Error: #{response.status} - #{response.reason_phrase}"
      when 500..599
        # Server error: API failure
        puts "Error: #{response.status} - #{response.reason_phrase}"
        puts "Details: #{response.body}"
      else
        # Handle other status codes
        puts "Unexpected error: #{response.status} - #{response.reason_phrase}"
      end
    redirect_to root_path
  end
end

client/app/helpers/application_helper.rb
module ApplicationHelper
end

client/app/helpers/home_helper.rb
module HomeHelper
end

client/app/views/home/home.html.erb
<h1>Home Page</h1>

<p>Create a post</p>
<%= form_with(url: create_post_path, method: :post) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :text %>
  <%= f.submit "Submit", disable_with: 'Submitting...' %>
<% end %>

<% @posts.each do |post| %>
  <h3><%= post["title"] %></h3>
  <h4><%= post["text"] %></h4>
<% end %>

client/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Client</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>